### ISSUE TITLE
Issue writing file to (__dirname+"/wave/"+req.body.wavename

### ISSUE THREAD

**Issue by tbuckham** [dsxsxsxs/uploadWAV#1]
Hi there

I've downloaded your app for a audio recorder/uploader test I was hoping to do (submitting the uploaded audio for analysis by an external API). Unfortunately I don't seem to be writing the recorded files succcessfully, so wondered if you might be able to advise?

On the client side I'm getting the console.log of object {rs : true} + the success prompt. However on the server command line I get the following response:

express server is running on: 3000
2017-06-29T08:19:12.101Z.wav
{ Error: ENOENT: no such file or directory, open 'C:\uploadWAV\wave\2017-06-29T08:19:12.101Z.wav'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\uploadWAV\\wave\\2017-06-29T08:19:12.101Z.wav' }

I setup a dir called in the app root folder, and added in 
    app.use(express.static(__dirname + '/wave/'));

however that doesn't seem to have changed anything - can you advise on what I might need to add/edit perhaps?

Thanks!

Tom

**Comment by dsxsxsxs** [comment]
You might make sure that the 'wave' directory does exists in ''C:\uploadWAV\'.
Good luck!

**Comment by tbuckham** [comment]
Thanks, sorry I missed your reply and only just noticed it via an update about the ticket being closed :)

**Comment by dsxsxsxs** [comment]
Never mind.
